
docker buildx version

docker buildx create --use
docker buildx inspect --bootstrap

aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URL}

docker buildx build \
  --platform=linux/arm64 \
  --load \
  -t "$ECR_URL:$TAG" .
  
docker push ${ECR_URL}:${TAG}