name: Create Pull Request

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true
    inputs:
      head_branch:
        type: string
        required: true
      base_branch:
        type: string
        required: true
      title:
        type: string
        required: true
      body:
        type: string
        required: true

jobs:
  create-pr:
    outputs:
      status: ${{ steps.create-pr.outputs.status || 'failure' }}
      pr_number: ${{ steps.create-pr.outputs.pr_number }}
      pr_url: ${{ steps.create-pr.outputs.pr_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GH_TOKEN for gh cli
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_OUTPUT

      - name: Check PR is already exist
        id: exist-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_exist=$(gh pr list \
            --base "$base_branch" \
            --head "$head_branch" \
            --json title)

          if [[ -n "$res" ]]; then
            pr_exist=true
          else
            pr_exist=false
          fi

          echo "pr_exist=$pr_exist" >> $GITHUB_OUTPUT

      - name: Create or Update PR
        id: create-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          if [[ ${{ steps.exist-pr.outputs.exist-pr == 'false' }} ]]; then
            echo "PR already exist"
            exit 0
          else
            pr_url=$(gh pr create \
              --head "${{ inputs.head_branch }}" \
              --base "${{ inputs.base_branch }}" \
              --title "${{ inputs.title }}" \
              --body "${{ inputs.body }}")
          fi

          pr_number=$(echo "$pr_url" | sed 's|.*/pull/\([0-9]*\)$|\1|')
          echo "pr_number=$pr_number"
          echo "pr_url=$pr_url"

          echo "status=success" >> $GITHUB_OUTPUT
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
