name: Create Pull Request

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true
    inputs:
      head_branch:
        type: string
        required: true
      base_branch:
        type: string
        required: true
      title:
        type: string
        required: true
      body:
        type: string
        required: true
    #
    outputs:
      pr_number:
        value: ${{ jobs.create-pr.outputs.pr_number }}
      pr_url:
        value: ${{ jobs.create-pr.outputs.pr_url }}
      result:
        value: ${{ jobs.create-pr.result }}

jobs:
  create-pr:
    outputs:
      pr_number: ${{ steps.create-pr.outputs.pr_number }}
      pr_url: ${{ steps.create-pr.outputs.pr_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR
        id: create-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          data=$(gh pr list \
            --base "$base_branch" \
            --head "$head_branch" \
            --json number,url)

          if [[ -n "$data" && "$data" != "[]" ]]; then
            pr_number=$(jq -r '.number' <<< "$resp")
            pr_url=$(jq -r '.url' <<< "$resp")
          else
            pr_url=$(gh pr create \
            --head "${{ inputs.head_branch }}" \
            --base "${{ inputs.base_branch }}" \
            --title "${{ inputs.title }}" \
            --body "${{ inputs.body }}")

            pr_number=$(echo "$pr_url" | sed 's|.*/pull/\([0-9]*\)$|\1|')
          fi

          #############################
          echo "pr_number=$pr_number"
          echo "pr_url=$pr_url"
          #############################

          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
