name: Create Pull Request

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true
    inputs:
      head_branch:
        type: string
        required: true
      base_branch:
        type: string
        required: true
      title:
        type: string
        required: true
      body:
        type: string
        required: true

jobs:
  create-pr:
    outputs:
      status: ${{ steps.create-pr.outputs.status || 'failure' }}
      pr_number: ${{ steps.create-pr.outputs.pr_number }}
      pr_url: ${{ steps.create-pr.outputs.pr_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GH_TOKEN for gh cli
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GH_TOKEN

      - name: Create PR
        id: create-pr
        run: |
          set -e

          pr_output=$(gh pr create \
            --head ${{ inputs.head_branch }} \
            --base ${{ inputs.base_branch }} \
            --title ${{ inputs.title }} \
            --body ${{ inputs.body }}
            --json number, url)

          pr_number=$(echo "$pr_output | jq -r '.number')
          pr_url=$(echo "$pr_output | jq -r '.url')

          echo "status=success" >> $GITHUB_OUTPUT
          echo "pr_number=$pr_number$" >> $GITHUB_OUTPUT
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
