name: Create Comment of Pull Request

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        description: "GitHub token"
        required: true
    inputs:
      body:
        type: string
        description: "PR Comment Body"
        required: true
      repository:
        type: string
        description: "Repository name"
        required: true
      pr_number:
        type: string
        description: "Pull Request number"
        required: true
jobs:
  create-comment:
    outputs:
      status: ${{ steps.create-pr.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -s --silent: hide progress bar of curl
      # -X --request: HTTP method, default: GET
      # -o --output: output file, default: stdout
      # -H --header: HTTP header
      # -d --data: HTTP body
      # -w --write-out: HTTP status code
      - name: Create PR Comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "${{ inputs.body }}" > input.txt

          gh pr comment ${{ inputs.pr_number }} \
            -F input.txt \
            -R ${{ inputs.repository }}

          # if [[ $? -eq 0 && "$resp" -ge 200 && "$resp" -lt 300 ]]; then
          #   echo "status=success" >> $GITHUB_OUTPUT
          # else
          #   echo "status=failure" >> $GITHUB_OUTPUT
          # fi
