name: Send Discord Message (Generalized)
on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        description: Discord Webhook URL
        required: true
    inputs:
      # discord_webhook_url:
      #   type: string
      #   description: "Discord Webhook URL"
      #   required: true
      title:
        type: string
        description: "Discord message title"
        required: true
      description:
        type: string
        description: "Discord message description"
        required: false
      status:
        type: string
        description: "Status of the message (success or failure)"
        required: true
      actor:
        type: string
        description: "GitHub actor (username)"
        required: true
      fields:
        type: string
        description: "Discord message embed fields (key:value,key:value)"
        required: true
      components:
        type: string
        description: "Discord message components (JSON format)"
        required: false
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install requests
      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK_URL: ${{ inputs.discord_webhook_url }}
          MESSAGE_TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          STATUS: ${{ inputs.status }}
          ACTOR: ${{ inputs.actor }}
          FIELDS: ${{ inputs.fields }}
          COMPONENTS: ${{ inputs.components }}
        run: |
          python .github/workflows/send-discord-message.py
