name: Send Discord Message (Generalized)
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        description: Slack Webhook URL
        required: true
    inputs:
      # discord_webhook_url:
      #   type: string
      #   description: "Discord Webhook URL"
      #   required: true
      title:
        type: string
        description: "Slack message title"
        required: true
      description:
        type: string
        description: "Slack message description"
        required: false
      status:
        type: string
        description: "Status of the message (success or failure)"
        required: true
      actor:
        type: string
        description: "GitHub actor (username)"
        required: true
      fields:
        type: string
        description: "Discord message embed fields (key:value,key:value)"
        required: true
      components:
        type: string
        description: "Discord message components (JSON format)"
        required: false
      debug:
        type: boolean
        description: "Debug mode"
        default: false
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zdpk/workflows
          ref: main
          path: tmp
          fetch-depth: 0
          sparse-checkout: scripts/send_discord_message
          sparse-checkout-cone-mode: true

      - name: Change Directory
        run: |
          cd tmp/scripts/send_discord_message
          echo "Changed directory to $(pwd)"
          echo "Listing files in $(ls -al)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install requests
      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TITLE: ${{ inputs.title }}
          DESCRIPTION: ${{ inputs.description }}
          STATUS: ${{ inputs.status }}
          ACTOR: ${{ inputs.actor }}
          FIELDS: ${{ inputs.fields }}
          COMPONENTS: ${{ inputs.components }}
          DEBUG: ${{ inputs.debug }}
        run: |
          python ./tmp/scripts/send_discord_message/main.py
